### PR TITLE
Remove alias method chain

### PR DESCRIPTION
**Pull request by davidgross**

### CODE REVIEW

**Comment by aaron** [comment]
@davidgross, looks like you are still working on this. Want me to hold off on review and merge?

**Comment by davidgross** [comment]
@aaron Yeah, should be ready in a few minutes.

**Comment by davidgross** [comment]
@aaron did you know this gem was not being tested? (anywhere)

**Comment by davidgross** [comment]
@aaron Now it's ready.

**Review by aaron — APPROVED** [review]

**Pull request merged**
